# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Neil Ross Daniel Manohar'
description: "Data Science Portfolio showcasing AI, Machine Learning, and NLP projects."

short_url: 'neildaniel221270.github.io'
google_analytics: #
disqus: #
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ""  # Since this is for your personal GitHub page

# Permalinks
permalink: /:title

# Gems and other configs
plugins: [jekyll-paginate]

# Settings for deploy rake task
# Username and repo of Github repo
safe: false
lsi: false
username: neildaniel221270  # Your GitHub username
repo: neildaniel221270.github.io  # Your repository name
branch: master
relative_source: ../jasper/
destination: ../jasper-pages/
production_url: https://neildaniel221270.github.io/
source_url: https://github.com/neildaniel221270/neildaniel221270.github.io

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
